type: task
name: nnunet-train
python: 3.10
resources:
  gpu: A100:1
spot_policy: auto
utilization_policy:
  min_gpu_utilization: 10
  time_window: 1h
volumes:
  - name: research-workspace
    path: /workspace
working_dir: /workspace/capstone
repos:
  - .
env:
  - nnUNet_raw=/workspace/capstone/data/nnunet/nnUNet_raw
  - nnUNet_preprocessed=/workspace/capstone/data/nnunet/nnUNet_preprocessed
  - nnUNet_results=/workspace/capstone/data/nnunet/nnUNet_results
commands:
  - uv pip install nnunetv2
  - nnUNetv2_train 501 ${CFG} 0 -p nnUNetPlans -device cuda


